[package]
name = "mslm"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.10.0-alpha.2", features = ["blocking", "json"] }
url = "2.2.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
